services:
  postgres:
    image: postgres:latest
    container_name: eco_route_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${SPRING_DATASOURCE_USERNAME}
      POSTGRES_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    container_name: eco_route_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_USERNAME}
      MINIO_ROOT_PASSWORD: ${MINIO_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio-data:/data

  vrp-api:
    image: ducvu0907/eco-route-vrp-api:latest
    container_name: eco_route_vrp_api
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: ${DATABASE_URL}
      ORS_API_KEY: ${ORS_API_KEY}
      PRETRAINED_PATH: ${PRETRAINED_PATH}

  backend:
    image: ducvu0907/eco-route-backend:latest
    container_name: eco_route_backend
    ports:
      - "8080:8080"
    depends_on:
      - postgres
      - minio
      - vrp-api
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SERVER_PORT: ${SERVER_PORT}

      SECRET_KEY: ${SECRET_KEY}
      ACCESS_TOKEN_EXPIRATION: ${ACCESS_TOKEN_EXPIRATION}

      VRP_API_URL: ${VRP_API_URL}

      FIREBASE_CREDENTIALS_PATH: ${FIREBASE_CREDENTIALS_PATH}
      FIREBASE_DATABASE_URL: ${FIREBASE_DATABASE_URL}

      MINIO_USERNAME: ${MINIO_USERNAME}
      MINIO_PASSWORD: ${MINIO_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      MINIO_BUCKET_NAME: ${MINIO_BUCKET_NAME}

  frontend:
    image: ducvu0907/eco-route-frontend:latest
    container_name: eco_route_frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  postgres-data:
  minio-data:
