spring:
  application:
    name: app
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/eco_route_db}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: update

server:
  port: ${SERVER_PORT:8080}

application:
  security:
    jwt:
      secret-key: ${SECRET_KEY:1af670eff96448b0c64d3ee1ae5939a25a9522ec6ae1fa192732b43e9fe8c29d}
      access-token-expiration: ${ACCESS_TOKEN_EXPIRATION:3600000} # milliseconds

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /docs
